apiVersion: apps/v1
kind: Deployment
metadata:
  name: vedified-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vedified-backend
  template:
    metadata:
      labels:
        app: vedified-backend
    spec:
      containers:
        - name: backend
          image: arshthakur07/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: vedified-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP