apiVersion: apps/v1
kind: Deployment
metadata:
  name: vedified-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vedified-mongo
  template:
    metadata:
      labels:
        app: vedified-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          emptyDir: {}  # For persistent storage, you can use PersistentVolumeClaim later
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: vedified-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP